### ISSUE TITLE
Team names

### ISSUE THREAD

**Issue by Taupinio** [Karthik99999/pmd-gen#1]
What happened to the box where you put the name of the rescue team that will rescue you?

**Comment by Taupinio** [comment]
Ok, you hard-coded it.

**Comment by Karthik99999** [comment]
To further clarify for others who happen to see this, the team name is hard coded to "pmd-gen" by default, and can be changed by clicking the "advanced options" on the bottom row of the rescue password generator popup. This was done to simplify password making, as most people probably wouldn't care about things like the team name, or the pokemon they are rescuing.

**Comment by Karthik99999** [comment]
just realized you were probably talking about the revival password generator popup. that was hardcoded to "pmd-gen" as well (for the same reasons as stated above). I could add a similar option to what the rescue password popup has to show the team name text box, or just show it anyway but type in "pmd-gen" by default.

**Comment by Taupinio** [comment]
Could you then add that similar option please?
Because I somehow cared about the revival password thing very much.

**Comment by Taupinio** [comment]
I did see now that you added it, so I will thank you for that.
