### ISSUE TITLE
Will this be updated? It won't give me a revival code despite entering it correctly

### ISSUE THREAD

**Issue by NymphieDust** [Karthik99999/pmd-gen#3]
I hope you have plans to maintain this, as I have not found another gen for this game. I cant get a revival code for this rescue code: 
6f 9e 5s 5h 5h 5e 4s 1w de dw 4e 4p ph ms 7s 2w mh mw 5e dw 8f xw 2e 8h 4h xw 4f 4s 6w 1w

**Comment by Karthik99999** [comment]
> 6f 9e 5s 5h 5h 5e 4s 1w de dw 4e **4p** ph ms 7s 2w mh mw 5e dw 8f xw 2e 8h 4h xw 4f 4s 6w 1w

`4p` is not a valid character. I know that the generator doesn't have a full 100% success rate, but the issue here should just be this typo.
