### ISSUE TITLE
All codes are expired

### ISSUE THREAD

**Issue by killerdevildog11** [Karthik99999/pmd-gen#4]
as of now all codes generated they are expired

**Comment by Riskae** [comment]
![image](https://github.com/user-attachments/assets/935ff532-5d18-402a-8540-d4e5ce9f8341)

Same issue

**Comment by Karthik99999** [comment]
> ![image](https://private-user-images.githubusercontent.com/178526356/358421475-935ff532-5d18-402a-8540-d4e5ce9f8341.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3NjM0MTQsIm5iZiI6MTcyMzc2MzExNCwicGF0aCI6Ii8xNzg1MjYzNTYvMzU4NDIxNDc1LTkzNWZmNTMyLTVkMTgtNDAyYS04NTQwLWQ0ZTVjZTlmODM0MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNVQyMzA1MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MzQ4MjBhOTg0NjRiMTMyZTE2NDU1NzU2MTQ3ODYwNWMyNTQ5MTdhZDJmZjJmZDg0M2IzNWYzMzU0MjA1ODU0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vA3D0JwbewUCD5_9tQt1kKG476N0wlf2UIBqZlANDy0)
> 
> Same issue

Is your switch clock and pc/phone (whatever device you are using to access the website) synced up? Timestamps are encoded into the password and the website uses the clock of your device so the clocks being wrong is the only reason I can think of off the top of my head as to why this is occuring.

**Comment by Riskae** [comment]
This was my issue, I forgot I had adjusted my system clock on the switch. Thank you so much!
