### ISSUE TITLE
Generated code is invalid

### ISSUE THREAD

**Issue by louvenarde** [Karthik99999/pmd-gen#9]
Hello, I'm not sure what exactly i'm doing wrong, but I can't seem to make this application work for PMD DX.
I've been stuck twice in a dungeon and both times this would generate unusable codes. The first time I gave my rescue code to a friend, who rescued me the "normal" way by entering the password on their own game, and the rescue code they gave me afterwards worked.

Now I'm stuck again in another dungeon, trying [https://karthik99999.github.io/pmd-gen/rtdx-revival](https://karthik99999.github.io/pmd-gen/rtdx-revival) , but just like the first time, it's not working.

This would be my rescue code:
![image](https://github.com/Karthik99999/pmd-gen/assets/33836535/0edc228e-1e24-4a04-9ade-97910fd2671c)

Which I typed on the website as `ps 6e 5h ps 9f mf pf 5f 6s 4e 2f 4s xf 4e 9f 1h pe mf 6s 2w ps 6h pe 2e me 3s 1s 3w 3h 6e` 

This is the revival code that I got:
![image](https://github.com/Karthik99999/pmd-gen/assets/33836535/59a45af2-35c5-4c09-ad25-0b0453018eae)

Upon validating it, the bird says "oops, you seem to have entered an invalid password."
I tried with different team names on the website, to no avail

**Comment by Karthik99999** [comment]
Turns out there were several bugs with how I was getting the revival value from a rescue password, part of which I will blame on javascript and the fact that I have to use `BigInt` 😅. I just pushed a commit that should hopefully fix this, let me know if there are still issues.

**Comment by louvenarde** [comment]
Works perfect, thanks a bunch <3
